apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  resource.customizations.health.Service: |
    hs = {}
    -- Always consider LoadBalancer service healthy in kind/local
    if obj.spec.type == "LoadBalancer" then
      hs.status = "Healthy"
      hs.message = "LoadBalancer service health check skipped (local cluster fallback)"
      return hs
    end
    -- Explicitly skip health check for admission service
    if obj.metadata.name == "ingress-nginx-controller-admission" then
      hs.status = "Healthy"
      hs.message = "Admission controller service health check skipped"
      return hs
    end
    return hs  -- fallback to default health check
  resource.customizations.health.networking.k8s.io_Ingress: |
    hs = {}
    if obj.status == nil or obj.status.loadBalancer == nil or obj.status.loadBalancer.ingress == nil then
      hs.status = "Healthy"
      hs.message = "Ingress has no loadBalancer.ingress; skipping health check in local environment"
      return hs
    end
    return hs  -- Fallback to default health check
