version: 3

set: [e, u, pipefail]

includes:
  clst: .taskfiles/Taskfile.cluster.yaml
  cgpt: .taskfiles/Taskfile.chatgpt.yaml
  argo: .taskfiles/Taskfile.argocd.yaml
  ctx: .taskfiles/Taskfile.context.yaml
  helm: .taskfiles/Taskfile.helm.yaml
  k: .taskfiles/Taskfile.kubectl.yaml

tasks:
  default:
    desc: Print how to use `task` and command
    cmd: task --list-all
