kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kdk-dev
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32080
        hostPort: 32080
      - containerPort: 32443
        hostPort: 32443
      - containerPort: 32500
        hostPort: 32500
