kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kdk-stg
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32081
        hostPort: 32081
      - containerPort: 32444
        hostPort: 32444
      - containerPort: 32501
        hostPort: 32501
