apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: http-echo
        args:
          - "-text=Hello from STG environment"
