apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-echo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/karrybit/kdk.git
    targetRevision: main
    path: applications/http-echo/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: http-echo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
